### PR TITLE
Consistency

### PR DESCRIPTION
**Pull request by xl-sec**
Hi, first of -- massive thanks for a great ezine!

For a summer project (I'm making a RSS generator to feed a slack bot) I wanted to parse all historic ezines and ran across a number of inconsistency -- typos, missing labels etc. I split it into multiple commits for clarity, feel free to merge, squash or ignore :)

### CODE REVIEW

**Comment by xl-sec** [comment]
Arrgh sorry, didn't know that all the commits to the branch would be included in the pull request, only the ones up to `2d0a99b` is relevant for consistency.

**Comment by Simpsonpt** [comment]
Wow, unexpected and fantastic! Thank you for this contribution. RSS was one of the most requested features. Thumbs up for the inconsistency fixes :)

The overall contribution looks excellent, although I am not "comfortable" with the workflows. Nevertheless, this deserves to be merged, and it is a great starting point for further improvements.

**Comment by xl-sec** [comment]
You're welcome :)

No worries, I wouldn't be comfortable with workflows from a random person on the internet either. Feel free to remove the workflows in this upstream repo and I'll keep them in mine. I'm happy to keep the RSS on my github, unless you want to host it yourself. (Do note that your current readme points to my repo)

**Comment by Simpsonpt** [comment]
I just moved your automation code to a testing branch, and yes, I saw the readme update, and it makes sense (at least for now). Thank you once again :)

**Pull request merged**
